<!--
Nombre: [Diego GarcÃ­a Campos]
Curso: [ASIR1]
FECHA: [02/03/2025]
Ejercicio: [EJERCICIO BASCIO V XML]
-->

<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE colores [
<!ELEMENT colores (color*)>
<!ELEMENT color (nombreSvg,codigo)> <!--Se agrega el elemento color y sus respectivos hijoos-->
<!ELEMENT nombreSvg (#PCDATA)>
<!ELEMENT codigo (rgb | cmyk)> <!--Se agrega la opcion de que puedan ser cualquiera de las dos opciones-->
<!ELEMENT rgb (#PCDATA)>
<!ELEMENT cmyk (#PCDATA)>
]>

<colores>
    <color>
    <nombreSvg>Purple</nombreSvg>
    <codigo>
        <rgb>#800080</rgb>
    </codigo>
    </color>
    <color>
    <nombreSvg>Purple</nombreSvg>
    <codigo>
        <cmyk>#00FF007F</cmyk>
    </codigo>
    </color>
</colores>