<?xml version="1.0" encoding="UTF-8"?>

<!--
Nombre: [Diego García Campos]
Curso: [ASIR1]
FECHA: [02/03/2025]
Ejercicio: [EJERCICIO BASCIO V XML]
-->

<!DOCTYPE agenda [

    <!ELEMENT agenda (contacto*)>
    <!ELEMENT contacto (nombre, telefonoFijo*,telefonoMovil*)> <!--Si el móvil es opcional se cambia la cardinalidad-->
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT telefonoFijo (#PCDATA)>
    <!ELEMENT telefonoMovil (#PCDATA)>
]>

<agenda>
    <contacto>
        <nombre>Ayuntamiento</nombre>
        <telefonoFijo>010</telefonoFijo>
    </contacto>
    <contacto>
        <nombre>Emergencias</nombre>
        <telefonoFijo>112 (Unión Europea)</telefonoFijo> <!--Se cambia el orden segun el DTD-->
        <telefonoFijo>911 (Estados Unidos)</telefonoFijo>
        <telefonoMovil>Desconocido</telefonoMovil>
    </contacto>
</agenda>