<!--
Nombre: [Diego García Campos]
Curso: [ASIR1]
FECHA: [02/03/2025]
Ejercicio: [EJERCICIO BASCIO V XML]
-->

<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE contabilidad [
<!ELEMENT contabilidad (apunte*)> <!--Se detalla el elemento raiz-->
<!ELEMENT apunte (ingreso | gasto,fecha,cantidad,concepto)> <!--Se detallan todos los hijos-->
<!ELEMENT ingreso EMPTY>
<!ELEMENT gasto EMPTY> <!--Se detallan los elementos vacios-->
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT concepto (#PCDATA)>
]>

<contabilidad>
    <apunte>
        <ingreso />
        <fecha>24 de febrero de 2011</fecha>
        <cantidad>1800,00 €</cantidad>
        <concepto>Salario</concepto>
    </apunte>
    <apunte>
        <gasto />
        <fecha>28 de febrero de 2011</fecha>
        <cantidad>74,25 €</cantidad>
        <concepto>Recibo luz</concepto>
    </apunte>
</contabilidad>